# Create full conda environment that are used in the book notebooks
name: metpy_book
channels:
  - conda-forge
dependencies:
  - python<=3.13
  - numpy
  - shapely
  - matplotlib
  - scipy
  - pint
  - netcdf4
  - jupyter
  - jupyterlab
  - jupyter-book
  - cartopy
  - siphon
  - metpy
  - mystmd
  - xarray
  - urllib3
  - pandas
  - geopandas
  - nodejs
  - notebook
  - myst-nb
  - myst-parser
